### ISSUE TITLE
Исправление сайтов

### ISSUE THREAD

**Issue by e-shl** [Hokid/shikimorist#7]
1. У anidub два сайта https://online.anidub.com/ (при авторизации должен открывать заболоченные аниме, но сам сайт может быть заблокирован) и https://anime.anidub.life (аниме лицензируется/блокируется)
2. У anilibria настоящий сайт вот https://www.anilibria.tv/ , но работает только через VPN (это http://online.anilibria.life какой-то фейк с непонятным содержимым). Также https://darklibria.it/mirror .
3. А https://online.animedia.tv перебрасывает на https://m36.animedia.pro/

**Comment by e-shl** [comment]
Для таких случаев хорошобы иметь у расширения настройки ручной смены домена.

**Comment by Hokid** [comment]
anilibria.tv добавлена, остальное не актуально
