### ISSUE TITLE
Переход на shikimori

### ISSUE THREAD

**Issue by e-shl** [Hokid/shikimorist#8]
Иногда не охота добавлять аниме в список, но охота посмотреть информацию на Шики.
Для этого предлагаю сделать ссылку на страницу с аниме или лучше само название кликабельным
![image](https://user-images.githubusercontent.com/35057681/118855365-23aa7400-b8ef-11eb-8ebf-93b4befa24f6.png)
P.S. Уже давно https://shikimori.one/
![image](https://user-images.githubusercontent.com/35057681/118855620-63715b80-b8ef-11eb-87f8-642f8b8b5c42.png)

**Comment by Hokid** [comment]
Готово! В ближайщее время будет доступно после публикации версии 1.5.0.
